version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t simpleapi:latest .
      - docker tag portfolio:latest 819886478379.dkr.ecr.us-east-1.amazonaws.com/app-portfolio
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 819886478379.dkr.ecr.us-east-1.amazonaws.com/app-portfolio
