server:
  port: 8080
spring:
  application:
    name: chris-portfolio
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
aws:
  s3:
    bucket:
      name: chris-portfolio-blog-bucket
      contactme:
        prefix: messages/
  sns:
    contactme:
      sns: arn:aws:sns:us-east-1:819886478379:contact-me-message