server:
  port: 8080
spring:
  application:
    name: my-app
  datasource:
    url: jdbc:h2:mem:portfoliodb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        SQL: debug

outbound:
  email: