CREATE TABLE IF NOT EXISTS contact_me_message (
  id VARCHAR(100) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS technical_blogs (
  id VARCHAR(100) PRIMARY KEY,
  author VARCHAR(100) NOT NULL,
  title VARCHAR(100) NOT NULL,
  date VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL
);
